openapi: 3.0.1
info:
  title: cc-inv-meta
  description: Cloud Cognitive Data Platform for inventory meta data
  termsOfService: http://swagger.io/terms/
  contact:
    email: nobody@nowhere.com
  license:
    name: ""
    url: http://somwhere
  version: 0.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://cc-inv-meta-dev.mybluemix.net/cc-inv-meta
tags:
- name: meta_objects
  description: meta objects are the holders of the meta data. A meta_object describes
    the attributes of an entity such as warehouse, product, store in physcial world.
paths:
  /{tenant_id}/{meta_type}/meta_objects:
    parameters:
      - $ref: '#/components/parameters/tenant_id_param'
      - $ref: '#/components/parameters/meta_type_param'
      - in: query
        name: filter
        required: false
        schema:
          type: object
        description: filter by attributes
        examples:
          by-category: 
            value:
              category: "LIGHT-OIL-CRACKING"
          by-node-type:
            value:
              node-type: "seller"
    get:
      tags:
      - meta_objects
      summary: list meta_objects
      description: Get the complete list of meta_objects
      operationId: meta_objects-get
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/meta_object'
        400:
          description: Invalid status value
          content: {}
      security:
      - cc_inv_auth:
        - write:cc_inv
        - read:cc_inv
  /{tenant_id}/{meta_type}/meta_objects/{meta_object_id}:
    parameters:
    - $ref: '#/components/parameters/tenant_id_param'
    - $ref: '#/components/parameters/meta_type_param'
    - name: meta_object_id
      in: path
      description: ID of the meta_object
      required: true
      schema:
        type: string
    get:
      tags:
      - meta_objects
      summary: get a meta_object
      description: Get a meta_object by id
      operationId: meta_object-get
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/meta_object'
        500:
          description: Invalid input
          content: {}
      security:
      - cc_inv_auth:
        - write:cc_inv
        - read:cc_inv
    put:
      tags:
      - meta_objects
      summary: create/update a meta_object
      description: Create or update a meta_object
      operationId: meta_object-put
      requestBody:
        description: List of user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/meta_object'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/meta_object'
        500:
          description: Invalid input
          content: {}
      security:
      - cc_inv_auth:
        - write:cc_inv
        - read:cc_inv
      x-codegen-request-body-name: body
    delete:
      tags:
      - meta_objects
      summary: delete a meta_object
      description: Delete a meta_object by meta_object id
      operationId: meta_object-delete
      responses:
        200:
          description: successful operation
          content: {}
        500:
          description: Invalid input
          content: {}
      security:
      - cc_inv_auth:
        - write:cc_inv
        - read:cc_inv
components:
  schemas:
    meta-attribute:
      type: object
      properties:
        name:
          type: string
          description: name of the attribute
        value:
          type: string
          description: value of the attribute
    meta_object:
      type: object
      properties:
        meta_object_id:
          type: string
          description: id of the meta_object
        description:
          type: string
          description: description of the meta_object
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/meta-attribute'

  parameters:
    tenant_id_param: 
      name: tenant_id
      in: path
      description: ID of the tenant
      required: true
      schema:
        type: string
    meta_type_param:
      name: meta_type
      in: path
      description: Type of the meta
      required: true
      schema:
        type: string
      examples: 
        product:
          value: product
        warehouse:
          value: warehouse
        store:
          value: store
    
  securitySchemes:
    cc_inv_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:cc_inv: modify s4s entities
            read:cc_inv: read s4s entities
    api_key:
      type: apiKey
      name: api_key
      in: header
